# Generated by Django 6.0.6 on 2026-06-14 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("tracked_fields", models.JSONField(default=list)),
                (
                    "content_type",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "approval configuration",
                "verbose_name_plural": "approval configurations",
            },
        ),
        migrations.CreateModel(
            name="ChangeRequestField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveBigIntegerField(null=True)),
                ("field_name", models.CharField(max_length=255)),
                (
                    "change_type",
                    models.CharField(
                        choices=[("update", "update"), ("create", "create"), ("delete", "delete")], max_length=10
                    ),
                ),
                ("old_value", models.TextField(null=True)),
                ("new_value", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("approved", "approved"), ("rejected", "rejected")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_change_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_change_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "change request field",
                "verbose_name_plural": "change request fields",
                "ordering": ("-created",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("content_type", "object_id", "field_name"),
                        name="uniq_pending_lock_per_object_field",
                    )
                ],
            },
        ),
    ]
