# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_approve", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequestfield",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changerequestfield",
            name="payload_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="changerequestfield",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_change_fields",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="changerequestfield",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_change_fields",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequestfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("content_type", "payload_hash"),
                name="uniq_pending_create_per_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequestfield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("change_type", "update"),
                        ("payload__isnull", True),
                        ("payload_hash__isnull", True),
                        models.Q(("field_name", ""), _negated=True),
                        ("object_id__isnull", False),
                    ),
                    models.Q(
                        ("change_type", "create"),
                        ("payload__isnull", False),
                        ("payload_hash__isnull", False),
                        ("field_name", ""),
                        ("old_value__isnull", True),
                        ("new_value__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="changerequest_shape_by_change_type",
            ),
        ),
    ]
